### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by June222** [PNU-AID/AID_Backend_v2#17]
### 버그 설명
- dummy data 생성을 위해 migrations을 하려는 명령어 입력 시 발생하는 ERROR 
- appConfig에 label의 중복으로 인해 발생하는 오류임.
```bash
(aid-web-backend-v2-py3.10) PS C:\Users\admin\gitRepository\aid_web_backendv2\aid_web> python manage.py makemigrations
Traceback (most recent call last):
  File "C:\Users\admin\gitRepository\aid_web_backendv2\aid_web\manage.py", line 22, in <module>
    main()
  File "C:\Users\admin\gitRepository\aid_web_backendv2\aid_web\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\admin\gitRepository\aid_web_backendv2\.venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\admin\gitRepository\aid_web_backendv2\.venv\lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\Users\admin\gitRepository\aid_web_backendv2\.venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\admin\gitRepository\aid_web_backendv2\.venv\lib\site-packages\django\apps\registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: testapp
```

### 재현 방법
```bash
# 입력 시 발생
python manage.py makemigrations 
```

### 예상 동작
migrations이 정상적으로 진행되어야함.

### 스크린샷
<img width="976" alt="image" src="https://github.com/PNU-AID/AID_Backend_v2/assets/38900003/bfaa0c8a-595c-49f6-bc9d-b723d970fc3d">

### 추가 정보
[해결 Link](https://stackoverflow.com/questions/24319558/how-to-resolve-django-core-exceptions-improperlyconfigured-application-labels)가 stackoverflow에 있으나, 이 방법으로는 다른 오류를 또 일으키기도하고, 결론적으로 해결되지 않음.

**Comment by lijm1358** [comment]
#18 에서 해결되었습니다
